server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:mydb;mode=postgresql
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app:
  services:
    validation: http://localhost:8081